package com.projectscout;

public enum RootSignals {
    HAS_PACKAGE_JSON,
    HAS_README,
    HAS_ROOT_SRC,
    HAS_GIT_IGNORE,
    HAS_NODE_MODULES,
    HAS_YARN_LOCKFILE,
    HAS_NPM_LOCKFILE,
    HAS_PNPM_LOCKFILE,
    HAS_MULTIPLE_LOCKFILES,
    HAS_LINTER,
    HAS_FORMATTER,
    HAS_TYPESCRIPT_CONFIG,
    HAS_ASTRO_CONFIG,
    HAS_NEXT_CONFIG,
    HAS_VITE,
    HAS_WEBPACK,
    HAS_MULTIPLE_BUNDLERS,
    HAS_ENV_FILE,
}